#!/usr/bin/env bash
# Setup Zammad connection config
# Usage: zammad-setup.sh <base_url> <api_token>
#        zammad-setup.sh --show          # show current config
#        zammad-setup.sh --reset         # remove config
set -euo pipefail

ZAMMAD_CONFIG_FILE="${ZAMMAD_CONFIG_FILE:-$HOME/.zammad-config}"

case "${1:-}" in
  --show)
    if [ -f "$ZAMMAD_CONFIG_FILE" ]; then
      echo "Config file: $ZAMMAD_CONFIG_FILE"
      echo "---"
      cat "$ZAMMAD_CONFIG_FILE"
    else
      echo "No config file found at $ZAMMAD_CONFIG_FILE"
      echo "Env ZAMMAD_URL=${ZAMMAD_URL:-<not set>}"
      echo "Env ZAMMAD_TOKEN=${ZAMMAD_TOKEN:+<set>}${ZAMMAD_TOKEN:-<not set>}"
    fi
    exit 0
    ;;
  --reset)
    if [ -f "$ZAMMAD_CONFIG_FILE" ]; then
      rm "$ZAMMAD_CONFIG_FILE"
      echo "Config removed: $ZAMMAD_CONFIG_FILE"
    else
      echo "No config file to remove."
    fi
    exit 0
    ;;
  "")
    echo "Usage: zammad-setup.sh <base_url> <api_token>"
    echo "       zammad-setup.sh --show"
    echo "       zammad-setup.sh --reset"
    exit 1
    ;;
esac

BASE_URL="${1:?Missing base URL}"
API_TOKEN="${2:?Missing API token}"

# Strip trailing slash
BASE_URL="${BASE_URL%/}"

cat > "$ZAMMAD_CONFIG_FILE" <<EOF
# Zammad API Configuration
# Generated by zammad-setup.sh on $(date +%Y-%m-%d)
ZAMMAD_URL="${BASE_URL}"
ZAMMAD_TOKEN="${API_TOKEN}"
EOF

chmod 600 "$ZAMMAD_CONFIG_FILE"

echo "Zammad config saved to $ZAMMAD_CONFIG_FILE"
echo "  URL:   ${BASE_URL}"
echo "  Token: ${API_TOKEN:0:8}..."

# Quick connectivity test
echo ""
echo "Testing connection..."
RESPONSE=$(curl -sf --max-time 10 \
  -H "Authorization: Token token=${API_TOKEN}" \
  -H "Content-Type: application/json" \
  "${BASE_URL}/api/v1/users/me" 2>&1) && {
  echo "Connection successful!"
  echo "$RESPONSE" | python3 -c "
import json, sys
u = json.load(sys.stdin)
print(f\"  Logged in as: {u.get('firstname','')} {u.get('lastname','')} ({u.get('email','')})\")" 2>/dev/null || true
} || {
  echo "WARNING: Connection test failed. Check URL and token."
}
